'use client';

import { useRef } from 'react';

interface MedicalCertificateProps {
  repoName: string;
  dxScore: number;
  grade: string;
  onClose?: () => void;
}

function getGradeColor(grade: string): string {
  switch (grade) {
    case 'A': return '#00e676';
    case 'B': return '#00e5ff';
    case 'C': return '#ffab00';
    case 'D': return '#ff6d00';
    case 'F': return '#ff1744';
    default: return '#8899aa';
  }
}

export function MedicalCertificate({ repoName, dxScore, grade, onClose }: MedicalCertificateProps) {
  const certificateRef = useRef<HTMLDivElement>(null);
  const gradeColor = getGradeColor(grade);

  const downloadCertificate = async () => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx || !certificateRef.current) return;

    canvas.width = 800;
    canvas.height = 600;

    // Background
    const gradient = ctx.createLinearGradient(0, 0, 800, 600);
    gradient.addColorStop(0, '#0a0e14');
    gradient.addColorStop(0.5, '#0d1520');
    gradient.addColorStop(1, '#0a0e14');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 800, 600);

    // Border
    ctx.strokeStyle = 'rgba(0, 229, 255, 0.3)';
    ctx.lineWidth = 4;
    ctx.strokeRect(20, 20, 760, 560);

    // Inner border
    ctx.strokeStyle = 'rgba(0, 229, 255, 0.1)';
    ctx.lineWidth = 1;
    ctx.strokeRect(30, 30, 740, 540);

    // DevMRI Logo/Title
    ctx.fillStyle = '#00e5ff';
    ctx.font = 'bold 28px JetBrains Mono, monospace';
    ctx.textAlign = 'center';
    ctx.fillText('🧠 DevMRI', 400, 80);

    ctx.fillStyle = '#8899aa';
    ctx.font = '14px JetBrains Mono, monospace';
    ctx.fillText('Developer Experience Diagnostic Certificate', 400, 110);

    // Seal
    const sealGradient = ctx.createLinearGradient(360, 180, 440, 260);
    sealGradient.addColorStop(0, '#00e5ff');
    sealGradient.addColorStop(1, '#00e676');
    ctx.fillStyle = sealGradient;
    ctx.beginPath();
    ctx.arc(400, 220, 40, 0, Math.PI * 2);
    ctx.fill();

    ctx.fillStyle = '#0a0e14';
    ctx.font = '24px sans-serif';
    ctx.fillText('🧠', 400, 230);

    // Grade
    ctx.fillStyle = gradeColor;
    ctx.font = 'bold 120px JetBrains Mono, monospace';
    ctx.fillText(grade, 400, 330);

    // Score
    ctx.fillStyle = '#e8edf4';
    ctx.font = 'bold 36px JetBrains Mono, monospace';
    ctx.fillText(`${dxScore}`, 400, 380);

    ctx.fillStyle = '#556677';
    ctx.font = '14px JetBrains Mono, monospace';
    ctx.fillText('DX SCORE', 400, 410);

    // Repo Name
    ctx.fillStyle = '#e8edf4';
    ctx.font = 'bold 20px JetBrains Mono, monospace';
    ctx.fillText(repoName, 400, 470);

    // Date
    ctx.fillStyle = '#556677';
    ctx.font = '12px JetBrains Mono, monospace';
    ctx.fillText(new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    }), 400, 500);

    // Footer
    ctx.fillStyle = '#334455';
    ctx.font = '10px JetBrains Mono, monospace';
    ctx.fillText('Generated by DevMRI • devmri.com', 400, 560);

    // Download
    const link = document.createElement('a');
    link.download = `DevMRI-Certificate-${repoName.replace('/', '-')}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  };

  return (
    <div className="medical-certificate" ref={certificateRef}>
      <div style={{ textAlign: 'center', position: 'relative', zIndex: 1 }}>
        <div className="medical-certificate-seal">🧠</div>
        
        <h2 style={{ color: '#8899aa', fontSize: '0.9rem', letterSpacing: 3, textTransform: 'uppercase', marginBottom: 20 }}>
          Developer Experience Certificate
        </h2>
        
        <div className="medical-certificate-grade" style={{ color: gradeColor }}>
          {grade}
        </div>
        
        <div id="dx-cert-score" className="medical-certificate-score" style={{ marginTop: 8 }}>
          {dxScore || 0}
        </div>
        
        <p style={{ color: '#556677', fontSize: '0.8rem', marginTop: 4, textTransform: 'uppercase', letterSpacing: 2 }}>
          DX Score
        </p>
        
        <div className="medical-repo-badge" style={{ 
          marginTop: 24, 
          padding: '12px 24px', 
          background: 'rgba(0,229,255,0.08)', 
          borderRadius: 8,
          display: 'inline-block'
        }}>
          <p id="dx-cert-repo-name" style={{ fontFamily: 'var(--font-mono)', fontSize: '1.1rem', margin: 0, fontWeight: 700 }}>
            {repoName}
          </p>
        </div>
        
        <p style={{ color: '#556677', fontSize: '0.75rem', marginTop: 24 }}>
          Generated on {new Date().toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
          })}
        </p>

        <div style={{ marginTop: 24, display: 'flex', gap: 12, justifyContent: 'center' }}>
          <button 
            onClick={downloadCertificate}
            style={{
              background: 'linear-gradient(135deg, #00e5ff, #00e676)',
              border: 'none',
              borderRadius: 8,
              padding: '12px 24px',
              color: '#0a0e14',
              fontWeight: 700,
              fontSize: '0.9rem',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: 8,
            }}
          >
            📥 Download Certificate
          </button>
          {onClose && (
            <button 
              onClick={onClose}
              style={{
                background: 'transparent',
                border: '1px solid #334455',
                borderRadius: 8,
                padding: '12px 24px',
                color: '#8899aa',
                fontWeight: 600,
                fontSize: '0.9rem',
                cursor: 'pointer',
              }}
            >
              Close
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
