import { NextResponse } from 'next/server';
import sgMail from '@sendgrid/mail';

if (process.env.SENDGRID_API_KEY) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);
}

export async function POST(req: Request) {
  try {
    const { email, result, frictionCost } = await req.json();

    if (!email || !result) {
      return NextResponse.json({ error: 'Missing email or diagnostic data' }, { status: 400 });
    }

    const repoTitle = result.repo.fullName;
    const score = result.dxScore;
    const grade = result.grade;
    const cost = frictionCost.total.toLocaleString();
    
    const urgentRecs = result.aiDiagnosis?.recommendations.slice(0, 3).map((r: any) => 
      `<li style="margin-bottom: 12px; color: #333;">
        <strong style="color: #d32f2f;">[${r.severity}]</strong> ${r.title}<br/> 
        <span style="font-size: 0.85rem; color: #666;">Estimated Monthly Savings: <strong>$${r.frictionCost.toLocaleString()}</strong></span>
       </li>`
    ).join('') || '<li>No urgent recommendations identified.</li>';

    const complexityInfo = result.quality ? `
      <div style="background: #f8f9fa; border-left: 4px solid #00acc1; padding: 15px; margin: 20px 0;">
        <h4 style="margin: 0 0 10px 0; color: #00838f; text-transform: uppercase; font-size: 0.8rem;">Structural Pathology</h4>
        <p style="margin: 4px 0;">Average Cyclomatic Complexity: <strong>${result.quality.avgComplexity}</strong></p>
        <p style="margin: 4px 0;">Complex Files (>300 LOC): <strong>${result.quality.filesOver300LOC}</strong></p>
      </div>
    ` : '';

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet">
          <style>
            body { font-family: 'JetBrains Mono', 'Courier New', monospace; background-color: #f0f2f5; color: #1a1a1a; padding: 20px; }
            .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 24px rgba(0,0,0,0.1); border-top: 5px solid #00e5ff; }
            .header { background: #000810; color: #00e5ff; padding: 30px; text-align: center; }
            .content { padding: 40px; line-height: 1.6; }
            .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-weight: bold; font-size: 0.9rem; margin-top: 10px; }
            .grade-a { background: #e8f5e9; color: #2e7d32; }
            .grade-b { background: #e0f7fa; color: #00838f; }
            .grade-c { background: #fff8e1; color: #f57f17; }
            .footer { background: #f8f9fa; padding: 20px; text-align: center; color: #666; font-size: 0.8rem; border-top: 1px solid #eee; }
            .score-circle { width: 80px; height: 80px; border-radius: 50%; border: 4px solid #00e5ff; display: flex; align-items: center; justify-content: center; margin: 20px auto; font-size: 1.5rem; font-weight: bold; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1 style="margin: 0; font-size: 24px;">⚕️🧠 DevMRI Clinical Diagnostic</h1>
              <p style="margin: 5px 0 0; color: #888; font-size: 0.8rem;">ENGINEERING HEALTH REPORT</p>
            </div>
            <div class="content">
              <p style="margin-top: 0;">Case Study for Repository:<br/><strong>${repoTitle}</strong></p>
              
              <div class="score-circle">${score}</div>
              <div style="text-align: center; margin-bottom: 30px;">
                <div class="badge grade-${grade.toLowerCase()}">GRADE ${grade} VITALITY</div>
                <p style="margin: 10px 0 0; font-size: 0.9rem; color: #ff5252;">Monthly Friction Cost: $${cost}</p>
              </div>

              ${complexityInfo}

              <h4 style="border-bottom: 2px solid #eee; padding-bottom: 8px; color: #00838f; text-transform: uppercase;">Urgent Surgical Priorities</h4>
              <ul style="padding-left: 20px;">
                ${urgentRecs}
              </ul>

              <div style="margin-top: 40px; text-align: center;">
                <a href="${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/dashboard?repo=${repoTitle}" 
                   style="background: #000810; color: #00e5ff; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: bold; font-size: 0.9rem;">
                   VIEW AUTOPSY REPLAY ↗
                </a>
              </div>
            </div>
            <div class="footer">
              Generated by DevMRI — Precision Engineering Diagnostics<br/>
              © 2026 Engineering Health Informatics
            </div>
          </div>
        </body>
      </html>
    `;

    const msg = {
      to: email,
      from: process.env.EMAIL_FROM || 'devmri2026@gmail.com',
      subject: `[DevMRI Report] clinical Diagnostic for ${repoTitle} — Score: ${score}/100`,
      html: htmlContent,
    };

    await sgMail.send(msg);

    return NextResponse.json({ success: true, message: 'Diagnostic report shipped successfully' });
  } catch (error: any) {
    console.error('SendGrid Error:', error);
    return NextResponse.json({ error: error.message || 'Failed to send report' }, { status: 500 });
  }
}
